on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

jobs:
  show:
    name: show var
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "${{ github.event.number }}"
