name: PR Flow

on:
  pull_request:

jobs:
  show:
    name: show var
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "${{ github.event.action }}"
          echo "${{ github.event.number }}"
          echo "done"
