name: Start PR

on:
  push:
    branches:
      - feature/*

permissions:
  pull-requests: write

jobs:
  show:
    name: Start PR
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - run: gh pr create --base main --head feature/def --title "PR from feat to main" --body "Content"
        env:
          GH_TOKEN: ${{ github.token }}
